### ISSUE TITLE
Create REST API swagger

### ISSUE THREAD

**Issue by cristianobaptista** [ponticlaro/bebop-core#5]
References:
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
- http://bfanger.nl/swagger-explained/#/swaggerObject
- https://github.com/swagger-api/swagger-codegen
- http://petstore.swagger.io/v2/swagger.json

**Comment by huntercross** [comment]
This is what I am used to using for Angular2 apps -

https://github.com/swagger-api/swagger-codegen

**Comment by cristianobaptista** [comment]
moved to https://github.com/ponticlaro/bebop-http-api/issues/3
